name: tests-talks

on:
  pull_request:
    paths:
      - "talks/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd talks && npm install && npm run test:ci
