name: tests-ads

on:
  pull_request:
    paths:
      - "ads/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ads && npm install && npm run test:ci
